### PR TITLE
libbpf: Update to latest version

### PR DESCRIPTION
**Pull request by chaudron**
Update libbpf to the latest version as advanced03-AF_XDP needs at
least commit 672ae75.

### CODE REVIEW

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Update libbpf to the latest version as advanced03-AF_XDP needs at
> least commit 672ae75.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/xdp-project/xdp-tutorial/pull/66
>
> -- Commit Summary --
>
>   * libbpf: Update to latest version
>
> -- File Changes --
>
>     M libbpf (2)
>
> -- Patch Links --
>
> https://github.com/xdp-project/xdp-tutorial/pull/66.patch
> https://github.com/xdp-project/xdp-tutorial/pull/66.diff
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xdp-project/xdp-tutorial/pull/66

I think there's a kernel header we need to sync as well before this will
work?

In file included from af_xdp_user.c:19:
../libbpf/src//root/usr/include/bpf/xsk.h: In function ‘xsk_ring_prod__needs_wakeup’:
../libbpf/src//root/usr/include/bpf/xsk.h:82:21: error: ‘XDP_RING_NEED_WAKEUP’ undeclared (first use in this function)
   82 |  return *r->flags & XDP_RING_NEED_WAKEUP;
      |                     ^~~~~~~~~~~~~~~~~~~~
../libbpf/src//root/usr/include/bpf/xsk.h:82:21: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [../common//common.mk:105: af_xdp_user] Error 1

**Comment by chaudron** [comment]
Yes it needs the correct Kernel headers dependency, so what I do when using the latest bfp-next is copy them:

sudo cp /data/linux_kernel/usr/include/linux/if_xdp.h /usr/include/linux
sudo cp /data/linux_kernel/usr/include/linux/xdp_diag.h /usr/include/linux

Guess only the if_xdp.h is needed!

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Yes it needs the correct Kernel headers dependency, so what I do when using the latest bfp-next is copy them:
>
> sudo cp /data/linux_kernel/usr/include/linux/if_xdp.h /usr/include/linux
> sudo cp /data/linux_kernel/usr/include/linux/xdp_diag.h /usr/include/linux
>
> Guess only the if_xdp.h is needed!

Right, so could you please amend the pull request to also add that in
headers/linux/? :)

**Comment by chaudron** [comment]
> Right, so could you please amend the pull request to also add that in headers/linux/? :)

So what is the process for the /headers/linux directory, are those copied from the latest bpf-next? If so I'll check the others also and update if needed.

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

>> Right, so could you please amend the pull request to also add that in headers/linux/? :)
>
> So what is the process for the /headers/linux directory, are those
> copied from the latest bpf-next? If so I'll check the others also and
> update if needed.

Yeah, we've just been copying them over from net-next/bpf-next whenever
we ran into a compilation issue like this. We're not really keeping them
rigorously updated, more on an as-needed basis you might say :)

**Comment by chaudron** [comment]
Ok, I've added the file it compiles fine now. Will soon be adding a vagrant example so we can easily find issues like this.

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Ok, I've added the file it compiles fine now. Will soon be adding a
> vagrant example so we can easily find issues like this.

Awesome, thanks!

**Pull request merged**
