### PR TITLE
Tutorial planned improvements to parsing

### PR DESCRIPTION
**Pull request by netoptimizer**
Going to LPC2019 very soon...

I didn't finish this work, so I'll just store the branch and create a PR so I don't forget about this ;-)
I'm not quite ready to merge this, as I've not tested it and even convinced myself this is a good idea.

### CODE REVIEW

**Comment by netoptimizer** [comment]
Hmmm... why does this PR also contain libbpf changes???

Perhaps, this is why I had funny issues in #72, they could likely happen when I was switching between branches?

**Comment by tohojo** [comment]
Guess you accidentally did a 'git add libbpf' somewhere? :)

**Comment by netoptimizer** [comment]
PR #168 is taking over from this PR.

**Comment by netoptimizer** [comment]
Fixed in #168

**Pull request closed without merging**
