### PR TITLE
Rework tutorials to use libxdp and libbpf 1.0

### PR DESCRIPTION
**Pull request by donaldh**

### CODE REVIEW

**Comment by netoptimizer** [comment]
For completeness these are the changes I see on xdp-tools git submodule:

``` diff
$ cd lib/xdp-tools
$ git diff
diff --git a/lib/libxdp/libxdp.3 b/lib/libxdp/libxdp.3
index 7300a53c8de1..030f35385f78 100644
--- a/lib/libxdp/libxdp.3
+++ b/lib/libxdp/libxdp.3
@@ -1,4 +1,4 @@
-.TH "libxdp" "3" "October  6, 2022" "v1.2.2" "libxdp - library for loading XDP programs" 
+.TH "libxdp" "3" "November 17, 2022" "v1.2.2" "libxdp - library for loading XDP programs" 
 
 .SH "NAME"
 libxdp \- library for attaching XDP programs and using AF_XDP sockets
diff --git a/xdp-loader/xdp-loader.8 b/xdp-loader/xdp-loader.8
index 4389ad6d3492..7b7d7fce200b 100644
--- a/xdp-loader/xdp-loader.8
+++ b/xdp-loader/xdp-loader.8
@@ -1,4 +1,4 @@
-.TH "xdp-loader" "8" "AUGUST  9, 2022" "V1.2.2" "XDP program loader"
+.TH "xdp-loader" "8" "AUGUST  9, 2022" "V1.2.2" "XDP program loader" 

```

I don't get where these strange changes to the dates happens to originate from...

**Comment by donaldh** [comment]
> I don't get where these strange changes to the dates happens to originate from...

I don't know either, but they shouldn't be included so I'll revert this change.

**Comment by tohojo** [comment]
Donald Hunter ***@***.***> writes:

>> I don't get where these strange changes to the dates happens to originate from...
>
> I don't know either, but they shouldn't be included so I'll revert
> this change.

Just add 'ignore = dirty' to .gitmodules under the lib/xdp-tools entry
(as is already done for the libbpf module).

**Comment by netoptimizer** [comment]
> @tohojo  writes:
> Just add 'ignore = dirty' to .gitmodules under the lib/xdp-tools entry (as is already done for the libbpf module).

I'm not sure this is a good idea.
I've run into issues when we wanted to update the submodule version, and because my/users local git tree had 'dirty' submodule, these change was not automatically getting git pull'ed.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer ***@***.***> writes:

>> @tohojo  writes:
>> Just add 'ignore = dirty' to .gitmodules under the lib/xdp-tools entry (as is already done for the libbpf module).
>
> I'm not sure this is a good idea.
> I've run into issues when we wanted to update the submodule version,
> and because my/users local git tree had 'dirty' submodule, these
> change was not automatically getting git pull'ed.

But that happens regardless, doesn't it? And 'git submodule update' will
complain? Maybe we could have a make target that always resets
submodules to the known checkout and state, and direct users to run that
if they encounter problems. 'make clobber' or something?

**Comment by donaldh** [comment]
I have pushed a commit to set EMACS="" when running configure in xdp-tools.

**Comment by netoptimizer** [comment]
Going to merge this.
I have not reviewed all the individual commits, but I trust Donald and Maryam.
And I can poke them if things break ;-)

**Pull request merged**
