### PR TITLE
Basic02: XDP hardware offload

### PR DESCRIPTION
**Pull request by netoptimizer**
I did a quick implementation of XDP hardware offloading, and added this as part of basic02.

I did basic testing on a Netronome NIC:
(lspci says:)  Ethernet controller: Netronome Systems, Inc. Device 4000

### CODE REVIEW

**Comment by netoptimizer** [comment]
I will appreciate some review from @Netronome people, like @qmonnet , @kuba-moo and @dcbeckett

**Comment by qmonnet** [comment]
Hey Jesper, the changes look good to me. I ran the experiments from `basic02-prog-by-name` with this branch and I confirm I can get the programs offloaded with just the `--offload-mode` option, that's cool! Selecting the ELF section and unloading the programs work as well. And the doc looks fine too.

Just a nit: adding the `-A` flag at the end of the line deactivates/cancels the `--offload-mode` option, maybe using both should be forbidden? Anyway that's a detail.

An additional note on the page related to dependencies: I noticed you mentioned that bpftool is not officially packaged for Debian/Ubuntu. This is correct of course, but if it can be of any help for the tutorials, note that we provide a .deb package on [our support website](https://help.netronome.com/support/solutions/articles/36000050009-agilio-ebpf-2-0-6-extended-berkeley-packet-filter) ([download link](https://help.netronome.com/helpdesk/attachments/36025601060)). It is statically linked, so it should work with any machine (it even has the NFP JIT disassembler, for what it's worth).

Thank you so much for mentioning HW offload in your tutorial!

**Comment by netoptimizer** [comment]
@qmonnet writes:
> 
> An additional note on the page related to dependencies: I noticed you mentioned that bpftool is not officially packaged for Debian/Ubuntu. This is correct of course, but if it can be of any help for the tutorials, note that we provide a .deb package on [our support website](https://help.netronome.com/support/solutions/articles/36000050009-agilio-ebpf-2-0-6-extended-berkeley-packet-filter) ([download link](https://help.netronome.com/helpdesk/attachments/36025601060)). It is statically linked, so it should work with any machine (it even has the NFP JIT disassembler, for what it's worth).
> 

Hi @qmonnet 

Could I ask you to create a PR that add these .deb package links to [setup_dependencies.org](https://github.com/xdp-project/xdp-tutorial/blob/master/setup_dependencies.org#recommended-tools)?

**Comment by qmonnet** [comment]
Sure!

**Comment by netoptimizer** [comment]
> Just a nit: adding the `-A` flag at the end of the line deactivates/cancels the `--offload-mode` option, maybe using both should be forbidden? Anyway that's a detail.
> 

Well, for this --auto-mode / -A it is on purpose.

A related issue is that these tutorial examples will not allow you to load multiple XDP program on the same interface, as the kernel does not allow *--native-mode* and *--skb-mode* to co-exist. But this is not true to *--offload-mode*, and I know Netronome do have use-cases where it makes sense to let HW offload what it is capable-of and then let a native-XDP prog handle the rest.

There this might also be a corner-cases of what *--force* then implies.

**Comment by qmonnet** [comment]
True, but I didn't think it fell within the scope of this tutorial :).

**Comment by netoptimizer** [comment]
> True, but I didn't think it fell within the scope of this tutorial :).

I agree, I'm just going to merge this part then, and leave the corner-cases for later.

**Pull request merged**
