### PR TITLE
Implement basic03-map-counter assignment

### PR DESCRIPTION
**Pull request by netoptimizer**
Basic implementation of basic03-map-counter

### CODE REVIEW

**Comment by netoptimizer** [comment]
Also introduce using common_kern_user.h

**Comment by tohojo** [comment]
Hmm, it bother me a bit that there's this much copy/paste reuse between lessons.
I fear we'll end up spending way too much time going back and revising each of
them.

We could perhaps expend a bit more "learning effort" on the loader in the first
"lesson" and make it reusable between parts?

Alternatively, we could adopt a model where we ask the "student" to bring
forward their own loader between lessons. I.e., provide the example source code
in the first lesson, and when more features are needed in subsequent lessons,
instruct students to copy it themselves from previous lessons and add the
features (providing code snippets as needed, but not full source code)?

**Comment by netoptimizer** [comment]
> Hmm, it bother me a bit that there's this much copy/paste reuse between lessons.
> I fear we'll end up spending way too much time going back and revising each of
> them.

We should move the common_user.{c,h} files into ../basic_common/ or even ../common/, as they are generic and can be shared, the non-common argument are controlled by struct option long_options[] in start of C-files.

As we progress, then we can move the functions like load_bpf_object_file(), xdp_unload() and xdp_load() into another C-file on ../common/  when we don't want participants to see these any-longer.

**Comment by netoptimizer** [comment]
Going to merge this so I can continue working on more assignments

**Pull request merged**
